version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=human_weight
      - POSTGRES_PASSWORD=human_weight
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/human_weight
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db:
    driver: local